INSERT INTO MOVIES(ID,TITLE, LENGTH, PRODUCTION_DATE,COUNTRY) VALUES (1,'Szeregowiec Ryan',163,1998,'USA');

INSERT INTO PERSONS(ID, NAME, LAST_NAME,COUNTRY,DATE_OF_BIRTH) VALUES (1, 'Steven', 'Spielberg','USA','18-12-1946');
INSERT INTO PERSONS(ID, NAME, LAST_NAME,COUNTRY,DATE_OF_BIRTH) VALUES (2, 'Tom', 'Hanks','USA','09-07-1956');

INSERT INTO MOVIE_DIRECTORS VALUES (1,1);
INSERT INTO MOVIE_CAST VALUES (1,2);

INSERT INTO MOVIE_GENRES VALUES (1,'DRAMA');
INSERT INTO MOVIE_GENRES VALUES (1,'ACTION');

